services:
  - type: web
    name: shopkart
    env: python

    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput

    startCommand: gunicorn myproject.wsgi:application

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings
      - key: DEBUG
        value: "True"
      - key: PYTHON_VERSION
        value: 3.11
