# Generated by Django 5.2.3 on 2025-07-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
