# Generated by Django 5.2.3 on 2025-07-26 14:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_prod_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
