# Generated by Django 5.2.3 on 2025-07-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_prod_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catog',
            name='image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
