# Generated by Django 5.2.3 on 2025-07-26 15:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_catog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catog',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
